-- ============================================
-- TechZone Database Schema (Supabase) - FRESH
-- ============================================
-- WARNING: This drops ALL old tables and recreates them.
-- Execute this in Supabase SQL Editor.

-- ===== DROP OLD TABLES =====
DROP TABLE IF EXISTS public.audit_logs CASCADE;
DROP TABLE IF EXISTS public.repair_bookings CASCADE;
DROP TABLE IF EXISTS public.contact_messages CASCADE;
DROP TABLE IF EXISTS public.reviews CASCADE;
DROP TABLE IF EXISTS public.repair_services CASCADE;
DROP TABLE IF EXISTS public.coupons CASCADE;
DROP TABLE IF EXISTS public.order_items CASCADE;
DROP TABLE IF EXISTS public.orders CASCADE;
DROP TABLE IF EXISTS public.products CASCADE;
DROP TABLE IF EXISTS public.categories CASCADE;
DROP TABLE IF EXISTS public.settings CASCADE;
DROP TABLE IF EXISTS public.app_users CASCADE;

-- ===== 1. Users =====
CREATE TABLE public.app_users (
    id TEXT PRIMARY KEY,
    full_name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    phone TEXT,
    role TEXT NOT NULL DEFAULT 'customer',
    status TEXT NOT NULL DEFAULT 'active',
    password_hash TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT timezone('utc', now())
);

-- ===== 2. Categories =====
CREATE TABLE public.categories (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    icon TEXT,
    parent_id TEXT,
    image TEXT,
    description TEXT,
    status TEXT DEFAULT 'active',
    sort_order INTEGER DEFAULT 0,
    slug TEXT,
    show_in_navbar BOOLEAN DEFAULT true
);

-- ===== 3. Products =====
CREATE TABLE public.products (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    category_id TEXT, -- nullable
    product_type TEXT DEFAULT 'physical',
    brand TEXT,
    price NUMERIC NOT NULL,
    discount_price NUMERIC DEFAULT 0,
    quantity INTEGER NOT NULL DEFAULT 0,
    rating NUMERIC DEFAULT 0,
    sold INTEGER DEFAULT 0,
    status TEXT DEFAULT 'active',
    description TEXT,
    specs JSONB DEFAULT '[]'::jsonb,
    images JSONB DEFAULT '[]'::jsonb,
    variants JSONB DEFAULT '[]'::jsonb,
    low_stock_alert INTEGER DEFAULT 5,
    created_at TIMESTAMPTZ DEFAULT timezone('utc', now()),
    updated_at TIMESTAMPTZ DEFAULT timezone('utc', now())
);

-- ===== 4. Orders =====
CREATE TABLE public.orders (
    id TEXT PRIMARY KEY,
    user_id TEXT,
    customer_name TEXT,
    customer_phone TEXT,
    customer_email TEXT,
    total NUMERIC NOT NULL,
    status TEXT NOT NULL DEFAULT 'awaiting_delivery',
    delivery_method TEXT,
    payment_method TEXT,
    shipping_fee NUMERIC DEFAULT 0,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc', now())
);

-- ===== 5. Order Items =====
CREATE TABLE public.order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id TEXT NOT NULL,
    product_id TEXT NOT NULL,
    product_name TEXT,
    qty INTEGER NOT NULL DEFAULT 1,
    price NUMERIC NOT NULL
);

-- ===== 6. Settings =====
CREATE TABLE public.settings (
    id INTEGER PRIMARY KEY,
    data JSONB NOT NULL
);

-- ===== 7. Coupons =====
CREATE TABLE public.coupons (
    id TEXT PRIMARY KEY,
    code TEXT UNIQUE NOT NULL,
    type TEXT NOT NULL,
    value NUMERIC NOT NULL,
    min_order NUMERIC DEFAULT 0,
    max_uses INTEGER DEFAULT 0,
    used_count INTEGER DEFAULT 0,
    status TEXT DEFAULT 'active',
    expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT timezone('utc', now())
);

-- ===== 8. Repair Services (NEW) =====
CREATE TABLE public.repair_services (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT,
    description TEXT,
    price NUMERIC DEFAULT 0,
    duration TEXT,
    icon TEXT,
    status TEXT DEFAULT 'active',
    created_at TIMESTAMPTZ DEFAULT timezone('utc', now())
);

-- ===== 9. Repair Bookings =====
CREATE TABLE public.repair_bookings (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT NOT NULL,
    email TEXT,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    service_id TEXT,
    service_name TEXT,
    device TEXT,
    description TEXT,
    preferred_date DATE,
    mode TEXT,
    address TEXT,
    status TEXT DEFAULT 'pending',
    created_at TIMESTAMPTZ DEFAULT timezone('utc', now())
);

CREATE INDEX IF NOT EXISTS idx_repair_bookings_user_id
ON public.repair_bookings(user_id);

-- ===== 10. Contact Messages (NEW) =====
CREATE TABLE public.contact_messages (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    service_type TEXT,
    message TEXT,
    status TEXT DEFAULT 'new',
    created_at TIMESTAMPTZ DEFAULT timezone('utc', now())
);

-- ===== 11. Reviews =====
CREATE TABLE public.reviews (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name TEXT NOT NULL,
    role TEXT,
    text TEXT NOT NULL,
    rating INT DEFAULT 5 CHECK (rating BETWEEN 1 AND 5),
    product TEXT,
    status TEXT DEFAULT 'active',
    sort_order INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT timezone('utc', now())
);

-- ===== 12. Audit Logs =====
CREATE TABLE public.audit_logs (
    id TEXT PRIMARY KEY,
    action TEXT NOT NULL,
    actor_id TEXT,
    details JSONB,
    timestamp TIMESTAMPTZ DEFAULT timezone('utc', now())
);


-- ============================================
-- ENABLE ROW LEVEL SECURITY (open access)
-- ============================================
ALTER TABLE public.app_users ENABLE ROW LEVEL SECURITY;
CREATE POLICY "allow_all_app_users" ON public.app_users FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "allow_all_categories" ON public.categories FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
CREATE POLICY "allow_all_products" ON public.products FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
CREATE POLICY "allow_all_orders" ON public.orders FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "allow_all_order_items" ON public.order_items FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "allow_all_settings" ON public.settings FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

ALTER TABLE public.coupons ENABLE ROW LEVEL SECURITY;
CREATE POLICY "allow_all_coupons" ON public.coupons FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

ALTER TABLE public.repair_services ENABLE ROW LEVEL SECURITY;
CREATE POLICY "allow_all_repair_services" ON public.repair_services FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

ALTER TABLE public.repair_bookings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "allow_all_repair_bookings" ON public.repair_bookings FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

ALTER TABLE public.contact_messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "allow_all_contact_messages" ON public.contact_messages FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;
CREATE POLICY "allow_public_read_reviews" ON public.reviews FOR SELECT TO anon, authenticated USING (status = 'active');
CREATE POLICY "allow_all_reviews" ON public.reviews FOR ALL TO authenticated USING (true) WITH CHECK (true);

ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "allow_all_audit_logs" ON public.audit_logs FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);


-- ============================================
-- ENABLE REALTIME on key tables
-- ============================================
ALTER PUBLICATION supabase_realtime ADD TABLE public.products;
ALTER PUBLICATION supabase_realtime ADD TABLE public.categories;
ALTER PUBLICATION supabase_realtime ADD TABLE public.orders;
ALTER PUBLICATION supabase_realtime ADD TABLE public.order_items;
ALTER PUBLICATION supabase_realtime ADD TABLE public.repair_services;
ALTER PUBLICATION supabase_realtime ADD TABLE public.repair_bookings;
ALTER PUBLICATION supabase_realtime ADD TABLE public.contact_messages;
ALTER PUBLICATION supabase_realtime ADD TABLE public.reviews;
ALTER PUBLICATION supabase_realtime ADD TABLE public.coupons;
ALTER PUBLICATION supabase_realtime ADD TABLE public.settings;


-- ============================================
-- SEED DATA
-- ============================================

-- Default Admin (password: Admin@123 → hash: h$78b5b9a1)
INSERT INTO public.app_users (id, full_name, email, phone, role, status, password_hash)
VALUES ('adm-1', 'المدير العام', 'admin@techzone.sa', '0500000000', 'super_admin', 'active', 'h$78b5b9a1');

-- Default Categories
INSERT INTO public.categories (id, name, icon) VALUES
('cat-laptops', 'لابتوبات', 'fa-laptop'),
('cat-desktops', 'أجهزة مكتبية', 'fa-desktop'),
('cat-gaming', 'أجهزة Gaming', 'fa-gamepad'),
('cat-accessories', 'إكسسوارات', 'fa-keyboard'),
('cat-monitors', 'شاشات', 'fa-tv'),
('cat-storage', 'تخزين', 'fa-hdd'),
('cat-networking', 'شبكات', 'fa-wifi'),
('cat-components', 'قطع غيار', 'fa-microchip');

-- Default Repair Services
INSERT INTO public.repair_services (id, name, category, description, price, duration, icon, status) VALUES
('srv-1', 'تنظيف وصيانة عامة', 'hardware', 'تنظيف داخلي وخارجي مع فحص شامل للجهاز', 100, '1-2 ساعة', 'fa-broom', 'active'),
('srv-2', 'تغيير شاشة لابتوب', 'hardware', 'استبدال شاشة اللابتوب المكسورة أو التالفة', 350, '2-4 ساعات', 'fa-desktop', 'active'),
('srv-3', 'إصلاح الماذربورد', 'hardware', 'تشخيص وإصلاح أعطال اللوحة الأم', 250, '1-3 أيام', 'fa-microchip', 'active'),
('srv-4', 'ترقية الرام', 'upgrade', 'إضافة أو ترقية ذاكرة الوصول العشوائي', 80, '30 دقيقة', 'fa-memory', 'active'),
('srv-5', 'تركيب SSD', 'upgrade', 'تركيب قرص SSD مع نقل النظام', 120, '1-2 ساعة', 'fa-hdd', 'active'),
('srv-6', 'إزالة فيروسات', 'software', 'فحص شامل وإزالة جميع الفيروسات والبرمجيات الخبيثة', 80, '1-2 ساعة', 'fa-shield-virus', 'active'),
('srv-7', 'تثبيت نظام تشغيل', 'software', 'تثبيت Windows أو Linux مع التعريفات والبرامج الأساسية', 100, '1-2 ساعة', 'fa-windows', 'active'),
('srv-8', 'استعادة بيانات', 'data', 'استعادة الملفات المحذوفة أو من أقراص تالفة', 200, '1-3 أيام', 'fa-database', 'active'),
('srv-9', 'تبديل بطارية لابتوب', 'hardware', 'استبدال بطارية اللابتوب بأخرى أصلية', 150, '30 دقيقة', 'fa-battery-full', 'active'),
('srv-10', 'تبديل كيبورد لابتوب', 'hardware', 'استبدال لوحة المفاتيح التالفة', 200, '1-2 ساعة', 'fa-keyboard', 'active');

-- Default Settings
INSERT INTO public.settings (id, data) VALUES (1, '{
    "company": {
        "name": "TechZone",
        "phone": "+966 50 123 4567",
        "email": "info@techzone.sa",
        "address": "شارع التقنية، حي الملك فهد، الرياض"
    },
    "payments": {
        "mada": true,
        "card": true,
        "applepay": true,
        "cod": true,
        "bank_transfer": true
    },
    "shipping": {
        "standardFee": 20,
        "freeAbove": 500
    },
    "deliveryModes": [
        {"id": "delivery", "name": "توصيل للمنزل", "fee": 20},
        {"id": "pickup", "name": "استلام من المحل", "fee": 0}
    ]
}'::jsonb);

UPDATE public.settings
SET data = data || '{
    "company": {
        "name": "TechZone",
        "slogan": "متجر وصيانة احترافية للأجهزة والخدمات التقنية."
    },
    "hero": {
        "trustBadge": "متجر وصيانة احترافية يخدم أكثر من 12,000 عميل",
        "title": "عالمك التقني",
        "titleHighlight": "يبدأ من هنا",
        "description": "نوفر لك أحدث الأجهزة والخدمات التقنية وتجارب صيانة وتجميع احترافية في مكان واحد."
    },
    "trustBar": [
        { "icon": "truck", "title": "توصيل مجاني", "subtitle": "للطلبات فوق 50 د.أ" },
        { "icon": "headphones", "title": "دعم متواصل", "subtitle": "فريق مختص لخدمتك" }
    ],
    "stats": [
        { "value": 12000, "suffix": "+", "label": "عميل نشط", "hint": "أفراد وشركات يثقون بخدماتنا", "icon": "user", "accent": "#22c55e", "glow": "rgba(34,197,94,0.24)" },
        { "value": 34000, "suffix": "+", "label": "طلبات منجزة", "hint": "تنفيذ متواصل بدقة وسرعة", "icon": "shopping-bag", "accent": "#38bdf8", "glow": "rgba(56,189,248,0.24)" },
        { "value": 24, "suffix": "h", "label": "متوسط وقت الصيانة", "hint": "تشخيص واضح ومتابعة أسرع", "icon": "clock", "accent": "#f59e0b", "glow": "rgba(245,158,11,0.2)" },
        { "value": 98, "suffix": "%", "label": "رضا العملاء", "hint": "تجربة موثوقة بعد كل طلب", "icon": "shield-check", "accent": "#34d399", "glow": "rgba(52,211,153,0.22)" }
    ],
    "customBuild": {
        "badge": "⚙️ تجميع احترافي",
        "title": "صمم جهاز",
        "titleHighlight": "أحلامك",
        "description": "نقدم خدمة تجميع أجهزة حسب الطلب مع أفضل القطع وتركيب احترافي واختبارات كاملة قبل التسليم.",
        "features": [
            "استشارة مجانية لاختيار القطع",
            "تركيب احترافي لترتيب الكيابل",
            "تثبيت نظام التشغيل والتعريفات الأساسية",
            "فحص شامل للحرارة والأداء قبل التسليم"
        ],
        "ctaLabel": "اطلب تجميعة الآن",
        "ctaHref": "/services"
    },
    "serviceFeatures": [
        { "icon": "zap", "title": "استجابة سريعة", "subtitle": "تشخيص أولي سريع للحالة" },
        { "icon": "shield-check", "title": "قطع أصلية", "subtitle": "جودة أعلى واعتمادية أفضل" },
        { "icon": "phone", "title": "متابعة واضحة", "subtitle": "تحديثات مستمرة على حالة الطلب" }
    ],
    "paymentMethods": [
        { "value": "cod", "label": "الدفع عند الاستلام" },
        { "value": "bank_transfer", "label": "تحويل بنكي" },
        { "value": "wallet", "label": "محفظة" }
    ],
    "deliveryMethods": [
        { "value": "delivery", "label": "توصيل" },
        { "value": "pickup", "label": "استلام من المحل" }
    ],
    "serviceTypes": [
        { "value": "صيانة عاجلة", "label": "صيانة عاجلة" },
        { "value": "تجميعة مخصصة", "label": "تجميعة مخصصة" },
        { "value": "ترقية جهاز", "label": "ترقية جهاز" },
        { "value": "تركيب شبكات", "label": "تركيب شبكات" },
        { "value": "تنصيب برمجيات", "label": "تنصيب برمجيات" }
    ],
    "navigation": {
        "headerBefore": [
            { "href": "/", "label": "الرئيسية" },
            { "href": "/products", "label": "المنتجات" },
            { "href": "/accessories", "label": "الإكسسوارات" }
        ],
        "headerAfter": [
            { "href": "/services", "label": "خدمات الصيانة" },
            { "href": "/contact", "label": "تواصل معنا" }
        ],
        "footerQuick": [
            { "href": "/", "label": "الرئيسية" },
            { "href": "/products", "label": "المنتجات" },
            { "href": "/accessories", "label": "الإكسسوارات" },
            { "href": "/subscriptions", "label": "الشحن والاشتراكات" },
            { "href": "/services", "label": "خدمات الصيانة" }
        ],
        "footerSupport": [
            { "href": "/dashboard", "label": "حسابي" },
            { "href": "/checkout", "label": "إتمام الشراء" },
            { "href": "/contact", "label": "التواصل" }
        ],
        "footerBar": [
            { "href": "/products", "label": "المنتجات" },
            { "href": "/contact", "label": "التواصل" }
        ],
        "mobilePrimary": [
            { "href": "/products", "label": "تسوق" },
            { "href": "/services", "label": "الصيانة" },
            { "href": "/subscriptions", "label": "الاشتراكات" },
            { "href": "/contact", "label": "التواصل" }
        ]
    }
}'::jsonb
WHERE id = 1;

INSERT INTO public.reviews (name, role, text, rating, product, status, sort_order) VALUES
('أحمد عبدالله', 'جيمنغ احترافي', 'خدمة ممتازة وتجميعة نظيفة جدًا. التجربة كانت سريعة وواضحة من البداية للنهاية.', 5, 'تجميعة مخصصة', 'active', 0),
('سارة محمد', 'مصممة', 'تم إصلاح الجهاز بسرعة وكانت المتابعة واضحة طوال فترة الصيانة.', 5, 'صيانة لابتوب', 'active', 1),
('خالد سعيد', 'صاحب عمل', 'أسعار مناسبة وتعامل احترافي وتجربة شراء مريحة جدًا.', 4, 'إكسسوارات وتقنيات', 'active', 2);

-- Sample Products
INSERT INTO public.products (id, name, category_id, brand, price, discount_price, quantity, rating, sold, status, description, specs, images) VALUES
('prod-1', 'لابتوب ASUS ROG Strix G16', 'cat-gaming', 'ASUS', 5499, 4999, 15, 4.8, 45, 'active',
 'لابتوب ألعاب قوي بمعالج Intel Core i7 الجيل 13 وكرت شاشة RTX 4060',
 '[{"key":"المعالج","value":"Intel Core i7-13650HX"},{"key":"الرام","value":"16GB DDR5"},{"key":"التخزين","value":"512GB NVMe SSD"},{"key":"كرت الشاشة","value":"NVIDIA RTX 4060 8GB"},{"key":"الشاشة","value":"16 بوصة FHD+ 165Hz"}]'::jsonb,
 '["https://placehold.co/400x300/1a1a2e/00d4ff?text=ASUS+ROG"]'::jsonb),
('prod-2', 'لابتوب HP Pavilion 15', 'cat-laptops', 'HP', 2999, 2699, 25, 4.5, 80, 'active',
 'لابتوب متعدد الاستخدامات مناسب للعمل والدراسة',
 '[{"key":"المعالج","value":"Intel Core i5-1335U"},{"key":"الرام","value":"8GB DDR4"},{"key":"التخزين","value":"256GB SSD"},{"key":"الشاشة","value":"15.6 بوصة FHD"}]'::jsonb,
 '["https://placehold.co/400x300/1a1a2e/a855f7?text=HP+Pavilion"]'::jsonb),
('prod-3', 'كمبيوتر مكتبي Dell OptiPlex', 'cat-desktops', 'Dell', 3200, 0, 10, 4.3, 30, 'active',
 'جهاز مكتبي مثالي للمكاتب والأعمال',
 '[{"key":"المعالج","value":"Intel Core i5-13400"},{"key":"الرام","value":"8GB DDR4"},{"key":"التخزين","value":"512GB SSD"}]'::jsonb,
 '["https://placehold.co/400x300/1a1a2e/10b981?text=Dell+OptiPlex"]'::jsonb),
('prod-4', 'شاشة Samsung Odyssey G5', 'cat-monitors', 'Samsung', 1299, 1099, 20, 4.6, 55, 'active',
 'شاشة ألعاب منحنية 27 بوصة بدقة QHD ومعدل تحديث 144Hz',
 '[{"key":"الحجم","value":"27 بوصة"},{"key":"الدقة","value":"2560x1440 QHD"},{"key":"معدل التحديث","value":"144Hz"},{"key":"نوع اللوحة","value":"VA"}]'::jsonb,
 '["https://placehold.co/400x300/1a1a2e/f59e0b?text=Samsung+G5"]'::jsonb),
('prod-5', 'كيبورد Razer BlackWidow V4', 'cat-accessories', 'Razer', 699, 599, 35, 4.7, 90, 'active',
 'كيبورد ميكانيكي للألعاب مع إضاءة RGB',
 '[{"key":"النوع","value":"ميكانيكي"},{"key":"السويتش","value":"Razer Green"},{"key":"الإضاءة","value":"RGB Chroma"}]'::jsonb,
 '["https://placehold.co/400x300/1a1a2e/22c55e?text=Razer+KB"]'::jsonb),
('prod-6', 'ماوس Logitech G502 X', 'cat-accessories', 'Logitech', 349, 299, 50, 4.9, 120, 'active',
 'ماوس ألعاب احترافي بأداء فائق',
 '[{"key":"الحساسية","value":"25,600 DPI"},{"key":"الأزرار","value":"13 زر قابل للبرمجة"},{"key":"الوزن","value":"89 غرام"}]'::jsonb,
 '["https://placehold.co/400x300/1a1a2e/ec4899?text=Logitech+G502"]'::jsonb),
('prod-7', 'SSD Samsung 990 Pro 1TB', 'cat-storage', 'Samsung', 499, 449, 40, 4.8, 70, 'active',
 'قرص تخزين NVMe فائق السرعة',
 '[{"key":"السعة","value":"1TB"},{"key":"السرعة","value":"7450 MB/s قراءة"},{"key":"الواجهة","value":"PCIe 4.0 NVMe"}]'::jsonb,
 '["https://placehold.co/400x300/1a1a2e/3b82f6?text=Samsung+SSD"]'::jsonb),
('prod-8', 'راوتر TP-Link AX5400', 'cat-networking', 'TP-Link', 599, 0, 18, 4.4, 25, 'active',
 'راوتر WiFi 6 بسرعة فائقة لتغطية شاملة',
 '[{"key":"المعيار","value":"WiFi 6 (802.11ax)"},{"key":"السرعة","value":"5400 Mbps"},{"key":"التغطية","value":"حتى 230 متر مربع"}]'::jsonb,
 '["https://placehold.co/400x300/1a1a2e/8b5cf6?text=TP-Link+AX5400"]'::jsonb);

-- End of Schema
